spring:
  datasource:
    url: jdbc:h2:file:~/lancamentos
    username: sa
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

integracao:
  correios:
    url: https://viacep.com.br/ws/
